import { defineField, defineType } from "sanity";
import { photo } from "./shared";

export default defineType({
  name: "homePage",
  title: "Home page",
  type: "document",
  groups: [
    { name: "hero", title: "Hero" },
    { name: "intro", title: "Intro" },
    { name: "sessions", title: "Sessions" },
    { name: "approach", title: "Approach" },
    { name: "testimonial", title: "Testimonial" },
    { name: "recentWork", title: "Recent work" },
    { name: "closing", title: "Closing" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    photo("heroImage", "Hero photograph"),
    defineField({ name: "heroHeading", title: "Hero heading", type: "string", group: "hero" }),
    defineField({ name: "heroSubline", title: "Hero subline", type: "string", group: "hero" }),
    defineField({ name: "introHeading", title: "Heading", type: "string", group: "intro" }),
    defineField({
      name: "introBody",
      title: "Body",
      type: "array",
      of: [{ type: "text", rows: 3 }],
      group: "intro",
    }),
    photo("introImage", "Intro photograph (left, sits lower)"),
    photo("introImageSecondary", "Intro photograph (right)"),
    defineField({
      name: "sessionsHeading",
      title: "Heading",
      type: "string",
      group: "sessions",
      description: "The session cards themselves are edited under Session types.",
    }),
    defineField({
      name: "showRecentWork",
      title: "Show the recent work section",
      type: "boolean",
      group: "recentWork",
      initialValue: false,
      description:
        "The row of portfolio photographs. Pick which photos appear by switching on 'Show on the home page' under Portfolio images.",
    }),
    defineField({ name: "approachHeading", title: "Heading", type: "string", group: "approach" }),
    defineField({
      name: "approachBody",
      title: "Body",
      type: "array",
      of: [{ type: "text", rows: 3 }],
      group: "approach",
    }),
    defineField({ name: "approachPullQuote", title: "Pull quote", type: "string", group: "approach" }),
    photo("approachImage", "Approach photograph"),
    defineField({
      name: "testimonial",
      title: "Testimonial",
      type: "reference",
      to: [{ type: "testimonial" }],
      group: "testimonial",
      description:
        "Which testimonial to show. The words themselves are edited under Testimonials. Leave empty to use the first one.",
    }),
    defineField({ ...photo("testimonialImage", "Backdrop photograph"), group: "testimonial" }),
    defineField({ name: "closingHeading", title: "Heading", type: "string", group: "closing" }),
    defineField({ name: "closingBody", title: "Body", type: "text", rows: 3, group: "closing" }),
    photo("closingImage", "Closing photograph"),
    defineField({ name: "seoTitle", title: "SEO title", type: "string", group: "seo" }),
    defineField({ name: "seoDescription", title: "Meta description", type: "text", rows: 3, group: "seo" }),
  ],
  preview: { prepare: () => ({ title: "Home page" }) },
});
